import {expect,test} from 'bun:test';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import lockfile from 'proper-lockfile';
import {withTempWorkspaceEnv} from '../helpers.js';
import {McpCodemodeController,resetMcpCodemodeRuntimeForTests,assertSelectedMcpOwner} from '../../src/agent-pool/mcp-codemode-runtime.js';
import {bindMcpBridgeOwner,createMcpBridgeOwner} from '../../src/agent-pool/mcp-bridge-owner.js';
import {hydrateMcpKeychainCredentials,resetMcpStartupStateForTests,prepareMcpServerEdit,writeMcpProjectOverride,createMcpConfigWriteAuthority,getMcpBridgeSnapshot} from '../../src/secure/mcp-keychain.js';
async function fixture(run:(h:ReturnType<typeof harness>,root:string)=>Promise<void>,options:Parameters<typeof harness>[0]={}){await withTempWorkspaceEnv('server-settings-',{},async ws=>{mkdirSync(join(ws.workspace,'.pi'),{recursive:true});mkdirSync(join(ws.workspace,'.piclaw'),{recursive:true});writeFileSync(join(ws.workspace,'.piclaw','config.json'),JSON.stringify({domains:{access:{mode:'single-user'},other:{keep:true}}}),{mode:0o600});writeFileSync(join(ws.workspace,'.pi','mcp.json'),JSON.stringify({settings:{future:{keep:true}},mcpServers:{demo:{command:'never-run',args:['private-arg'],protocolVersion:'auto'},other:{command:'never-run-other'}}}),{mode:0o600});resetMcpStartupStateForTests();resetMcpCodemodeRuntimeForTests();await hydrateMcpKeychainCredentials(ws.workspace,()=>{throw Error('Forbidden credentials');});const h=harness(options);try{await h.ready;await run(h,ws.workspace);}finally{await h.dispose();resetMcpStartupStateForTests();resetMcpCodemodeRuntimeForTests();}});}
function harness(options:{close?:()=>Promise<void>;reload?:()=>Promise<void>;resume?:()=>void;timeout?:number}={}){
 const events:string[]=[],owners:Array<ReturnType<typeof createMcpBridgeOwner>>=[],sessions:any[]=[];
 const ready=(async()=>{for(let n=0;n<2;n++){let shutdown:Array<()=>Promise<void>>=[];const api=()=>({on(event:string,fn:()=>Promise<void>){if(event==='session_shutdown')shutdown.push(fn);}});const owner=createMcpBridgeOwner((_lease,onLifecycle)=>()=>onLifecycle({async shutdown(){events.push(`close:${n}`);await options.close?.();}}),undefined,{requireLifecycle:true});owners.push(owner);await owner.extension.factory(api() as any);const published={extensions:[{path:'<inline:piclaw-mcp-owner>'}],errors:[]} as any;
 const session={async abort(){events.push(`abort:${n}`);},async prompt(){},dispose(){},getAllTools:()=>[{name:'codemode'}],getActiveToolNames:()=>['read'],setActiveToolsByName(){},async reload(input:any){events.push(`reload:${n}`);for(const fn of shutdown)await fn();shutdown=[];await options.reload?.();await owner.extension.factory(api() as any);await input.beforeSessionStart();events.push(`started:${n}`);}};bindMcpBridgeOwner(session,{getExtensions:()=>published} as any,owner);sessions.push(session);}})();
 const manager={blockMcpAdmissions(){events.push('fence');},async fenceMcpAndSnapshot(){return sessions.map(session=>({session})) as any;},resumeMcpAdmissions(){events.push('resume');options.resume?.();},async quarantineMcpRuntime(){events.push('quarantine');}};
 const controller=new McpCodemodeController(manager,options.timeout??1000);
 return{ready,controller,events,sessions,async dispose(){for(const owner of owners)owner.dispose();await Bun.sleep(0);},input(edit:unknown){const response=controller.inspectServers(edit);return{revision:response.revision,acknowledgeInterruptions:true};}};
}
test('server Apply preserves private/advanced unrelated config, waits both ACKs, reloads both histories and consumes preview',async()=>fixture(async(h,root)=>{
 const original=JSON.parse(readFileSync(join(root,'.pi','mcp.json'),'utf8'));const input=h.input({name:'demo',action:'update',patch:{requestTimeoutMs:4000}});const result=await h.controller.applyServers(input,()=>{},new AbortController().signal);
 expect(result.phase).toBe('ready');expect(h.events.indexOf('reload:0')).toBeGreaterThan(h.events.indexOf('close:1'));expect(h.events.indexOf('resume')).toBeGreaterThan(h.events.indexOf('started:1'));expect(JSON.parse(readFileSync(join(root,'.pi','mcp.json'),'utf8'))).toEqual({...original,mcpServers:{...original.mcpServers,demo:{...original.mcpServers.demo,requestTimeoutMs:4000}}});expect(JSON.stringify(result)).not.toContain('private-arg');await expect(h.controller.applyServers(input,()=>{},new AbortController().signal)).rejects.toThrow('expired');
}));
test('exact inherited keychain credential cannot follow a repointed endpoint',async()=>fixture(async(h,root)=>{
 writeFileSync(join(root,'.mcp.json'),JSON.stringify({mcpServers:{remote:{url:'https://original.test/mcp',bearerTokenKeychain:'synthetic/key',bearerTokenEnv:'SYNTHETIC'}}}));await hydrateMcpKeychainCredentials(root,async()=>({secret:'SECRET_SENTINEL'} as any));expect(()=>h.input({name:'remote',action:'update',patch:{url:'https://new.test/mcp'}})).toThrow('inherited_credentials');expect(h.events).toEqual([]);
}));
test('owner revocation after all ACKs prevents rename and leaves runtime fenced',async()=>fixture(async(h,root)=>{
 const before=readFileSync(join(root,'.pi','mcp.json'),'utf8'),input=h.input({name:'demo',action:'update',patch:{disabled:true}});await expect(h.controller.applyServers(input,()=>{if(h.events.filter(e=>e.startsWith('close:')).length===2)throw Error('revoked');},new AbortController().signal)).rejects.toThrow('before configuration commit');expect(readFileSync(join(root,'.pi','mcp.json'),'utf8')).toBe(before);expect(h.events).not.toContain('resume');expect(()=>assertSelectedMcpOwner()).toThrow('blocked');
}));
test('codemode and server Apply share one phase and refuse overlap',async()=>{
 let finish!:()=>void;const gate=new Promise<void>(resolve=>{finish=resolve;});await fixture(async(h)=>{const input=h.input({name:'demo',action:'update',patch:{disabled:true}});const pending=h.controller.applyServers(input,()=>{},new AbortController().signal);await Bun.sleep(0);await expect(h.controller.apply({policy:{engine:'adapter',codemode:'on'},revision:h.controller.inspect().revision,acknowledgeInterruptions:true},()=>{})).rejects.toThrow('busy');finish();await pending;},{close:()=>gate});
});
test('failed reload after rename reports saved but unconfirmed and never resumes',async()=>fixture(async(h,root)=>{const input=h.input({name:'demo',action:'update',patch:{disabled:true}});await expect(h.controller.applyServers(input,()=>{},new AbortController().signal)).rejects.toThrow('configuration saved');expect(JSON.parse(readFileSync(join(root,'.pi','mcp.json'),'utf8')).mcpServers.demo.disabled).toBe(true);expect(h.events).not.toContain('resume');expect(()=>assertSelectedMcpOwner()).toThrow('blocked');},{reload:async()=>{throw Error('reload failure');}}));
test('removing override reveals inherited definition and disabling keeps it inert',async()=>fixture(async(h,root)=>{writeFileSync(join(root,'.mcp.json'),JSON.stringify({mcpServers:{demo:{command:'inherited-command'}}}));await hydrateMcpKeychainCredentials(root,()=>{throw Error('No secrets');});const preview=h.controller.inspectServers({name:'demo',action:'remove_override'});expect(preview.preview?.patch).toMatchObject({command:'inherited-command'});const prepared=prepareMcpServerEdit(root,{name:'demo',action:'update',patch:{disabled:true}});await writeMcpProjectOverride({workspaceDir:root,expectedRevision:getMcpBridgeSnapshot().revision,candidate:prepared.candidate,authority:createMcpConfigWriteAuthority({workspaceDir:root,authorise:()=>{},signal:new AbortController().signal})});expect(JSON.parse(readFileSync(join(root,'.pi','mcp.json'),'utf8')).mcpServers.demo.disabled).toBe(true);}));
test('deadline during post-rename unlock reports saved, keeps fenced, and observes the late write tail',async()=>{
 const original=lockfile.lock;let unlock!:()=>void;const tail=new Promise<void>(resolve=>{unlock=resolve;});
 try{lockfile.lock=(async(...args:Parameters<typeof original>)=>{const release=await original(...args);return async()=>{await release();await tail;};}) as typeof original;
 await fixture(async(h,root)=>{const input=h.input({name:'demo',action:'update',patch:{disabled:true}});await expect(h.controller.applyServers(input,()=>{},new AbortController().signal)).rejects.toThrow('configuration saved');expect(JSON.parse(readFileSync(join(root,'.pi','mcp.json'),'utf8')).mcpServers.demo.disabled).toBe(true);expect(h.events).not.toContain('resume');unlock();await Bun.sleep(0);expect(h.controller.inspect().runtime.observedPolicy).toBeNull();},{timeout:50});}
 finally{unlock?.();lockfile.lock=original;}
});
test('cancelled held ACK prevents any file write and captured public prompts stay denied',async()=>{
 let close!:()=>void;const cleanup=new Promise<void>(resolve=>{close=resolve;});await fixture(async(h,root)=>{const before=readFileSync(join(root,'.pi','mcp.json'),'utf8'),input=h.input({name:'demo',action:'update',patch:{disabled:true}}),abort=new AbortController();const pending=h.controller.applyServers(input,()=>{},abort.signal);await Bun.sleep(0);abort.abort(Error('cancelled'));await expect(pending).rejects.toThrow('before configuration commit');close();await Bun.sleep(0);expect(readFileSync(join(root,'.pi','mcp.json'),'utf8')).toBe(before);expect(h.events).not.toContain('resume');expect(()=>h.sessions[0].prompt()).toThrow();},{close:()=>cleanup});
});
test('new configured keychain reference failure after commit cannot be reported as applied',async()=>fixture(async(h,root)=>{
 const input=h.input({name:'remote',action:'update',patch:{url:'https://never-contact.test/mcp',auth:'bearer',bearerTokenKeychain:'missing-synthetic-entry',bearerTokenEnv:'SYNTHETIC_UNAVAILABLE_KEY'}});
 await expect(h.controller.applyServers(input,()=>{},new AbortController().signal)).rejects.toThrow('configuration saved');expect(JSON.parse(readFileSync(join(root,'.pi','mcp.json'),'utf8')).mcpServers.remote.bearerTokenKeychain).toBe('missing-synthetic-entry');expect(h.events).not.toContain('resume');expect(h.controller.inspect().runtime.observedPolicy).toBeNull();
}));
