import { expect, test } from 'bun:test';
import { normalizeIntelGpuSnapshots, formatOptionalPercent, formatOptionalBytesCompact, buildNullableSparklinePath, buildIntelGpuCompactSummaryParts } from '../../web/src/components/intel-gpu-meters.ts';
const gpu = (patch = {}) => ({id:'0000:00:02.0',name:'Intel GPU',provider:'intel-drm-fdinfo',driver:'i915',sample_time_ms:1000,status:'ok',reasons:[],busy_percent:63,engines:[{name:'render',capacity:1,busy_percent:63}],memory:{resident_bytes:677*1024**2,total_bytes:800*1024**2,shared_bytes:null},coverage:{clients:3,scanned_processes:100,unreadable_processes:0,unreadable_clients:0,truncated:false},history:[{timestamp_ms:0,busy_percent:null,resident_bytes:null},{timestamp_ms:1000,busy_percent:63,resident_bytes:677*1024**2}],...patch});
test('no GPU, no Intel rows or detail controls',()=>{expect(normalizeIntelGpuSnapshots(undefined)).toEqual([]);expect(normalizeIntelGpuSnapshots([])).toEqual([]);expect(buildIntelGpuCompactSummaryParts([])).toEqual([]);expect(normalizeIntelGpuSnapshots([{}])).toEqual([])});
test('null/invalid counters never become zero',()=>{for(const v of [null,undefined,'',NaN,-1,101])expect(formatOptionalPercent(v)).toBe('—');expect(formatOptionalPercent(0)).toBe('0%');expect(formatOptionalBytesCompact(null)).toBe('—');expect(formatOptionalBytesCompact(0)).toBe('0B')});
test('GPU rows preserve backend unknown headline and sparse histories',()=>{const [m]=normalizeIntelGpuSnapshots([gpu({busy_percent:null})],{nowMs:2000});expect(m.rows.busyText).toBe('—');expect(m.rows.residentText).toBe('677M');expect(m.rows.gpuLabel).toBe('GPU*');expect(m.coverageText).toContain('best-effort');expect(m.coverageText).not.toContain('coverage complete');expect(m.memoryWarningText).toContain('shared buffers');expect(m.rows.busySparkPath).not.toContain('NaN')});
test('stale samples and failed transport suppress current values and graphs',()=>{const [m]=normalizeIntelGpuSnapshots([gpu()],{nowMs:9000,lastSuccessAtMs:1000});expect(m.effectiveStatus).toBe('stale');expect(m.rows.busyText).toBe('—');expect(m.rows.residentText).toBe('—');expect(m.rows.busySparkPath).toBe('');expect(m.engines[0].busyPercent).toBeNull()});
test('multiple devices remain separate and unknown clients do not imply idle',()=>{const meters=normalizeIntelGpuSnapshots([gpu(),gpu({id:'0000:03:00.0',status:'unavailable',coverage:{clients:0}})],{nowMs:2000});expect(meters).toHaveLength(2);expect(meters[0].rows.gpuLabel).toBe('GPU0*');expect(meters[1].rows.busyText).toBe('—');expect(meters[1].noVisibleClientsText).toContain('No visible clients');expect(buildIntelGpuCompactSummaryParts(meters)).toHaveLength(4)});
test('nullable sparkline draws separate segments instead of bridging gaps',()=>{const p=buildNullableSparklinePath([20,null,60],56,16,{min:0,max:100});expect((p.match(/M /g)||[]).length).toBe(2);expect(p).not.toContain('NaN');expect(buildNullableSparklinePath([null,null])).toBe('')});
