/** Shared, data-only web palette catalogue. Core and both web skins consume identical IDs/colours. */
export type ThemeMode = "light" | "dark";
export interface ThemePalette {
  bgPrimary: string;
  bgSecondary: string;
  bgHover?: string;
  textPrimary: string;
  textSecondary: string;
  borderColor: string;
  accent: string;
  accentHover?: string;
  danger: string;
  success: string;
  warning?: string;
  syntax?: Record<string, string>;
  /** Authored ANSI roles; palette generation still enforces readable foregrounds. */
  terminal?: Record<string, string>;
  /** Preserve a single phosphor hue in contrast fallbacks and interaction overlays. */
  monochrome?: boolean;
}
export interface ThemePreset {
  id: string;
  label: string;
  mode: ThemeMode | "auto";
  light?: ThemePalette;
  dark?: ThemePalette;
  glow?: boolean;
  source?: string;
}
export const WEB_THEME_PRESETS: ThemePreset[] = [
  {
    id: "default",
    label: "Default",
    mode: "auto",
    light: {
      bgPrimary: "#ffffff",
      bgSecondary: "#f7f9fa",
      bgHover: "#e8ebed",
      textPrimary: "#0f1419",
      textSecondary: "#536471",
      borderColor: "#eff3f4",
      accent: "#1d9bf0",
      accentHover: "#1a8cd8",
      warning: "#f0b429",
      danger: "#f4212e",
      success: "#00ba7c",
    },
    dark: {
      bgPrimary: "#000000",
      bgSecondary: "#16181c",
      bgHover: "#1d1f23",
      textPrimary: "#e7e9ea",
      textSecondary: "#71767b",
      borderColor: "#2f3336",
      accent: "#1d9bf0",
      accentHover: "#1a8cd8",
      warning: "#f0b429",
      danger: "#f4212e",
      success: "#00ba7c",
      syntax: {
        keyword: "#1d9bf0",
        string: "#1d9bf0",
        number: "#1d9bf0",
        type: "#1d9bf0",
        definition: "#1d9bf0",
        property: "#1d9bf0",
        operator: "#e7e9ea",
      },
    },
  },
  {
    id: "tango",
    label: "Tango",
    mode: "light",
    light: {
      bgPrimary: "#f6f5f4",
      bgSecondary: "#efedeb",
      bgHover: "#e5e3e1",
      textPrimary: "#2e3436",
      textSecondary: "#5c6466",
      borderColor: "#d3d7cf",
      accent: "#3465a4",
      accentHover: "#2c5890",
      danger: "#cc0000",
      success: "#4e9a06",
    },
  },
  {
    id: "xterm",
    label: "XTerm",
    mode: "dark",
    dark: {
      bgPrimary: "#000000",
      bgSecondary: "#0a0a0a",
      bgHover: "#121212",
      textPrimary: "#d0d0d0",
      textSecondary: "#8a8a8a",
      borderColor: "#1f1f1f",
      accent: "#00a2ff",
      accentHover: "#0086d1",
      danger: "#ff5f5f",
      success: "#5fff87",
    },
  },
  {
    id: "monokai",
    label: "Monokai Original",
    mode: "dark",
    dark: {
      bgPrimary: "#272822",
      bgSecondary: "#2f2f2f",
      bgHover: "#2f2f2f",
      textPrimary: "#f8f8f2",
      textSecondary: "#cfcfc2",
      borderColor: "#3e3d32",
      accent: "#f92672",
      accentHover: "#f92672",
      danger: "#f92672",
      success: "#a6e22e",
      warning: "#e6db74",
      syntax: {
        keyword: "#f92672",
        string: "#e6db74",
        number: "#ae81ff",
      },
    },
    source: "https://monokai.pro/",
  },
  {
    id: "monokai-pro",
    label: "Monokai Pro",
    mode: "dark",
    dark: {
      bgPrimary: "#2d2a2e",
      bgSecondary: "#363237",
      bgHover: "#363237",
      textPrimary: "#fcfcfa",
      textSecondary: "#c1c0c0",
      borderColor: "#444046",
      accent: "#ff6188",
      accentHover: "#ff6188",
      danger: "#ff4f5e",
      success: "#a9dc76",
      warning: "#ffd866",
      syntax: {
        keyword: "#ff6188",
        string: "#ffd866",
        number: "#ab9df2",
      },
    },
    source: "https://monokai.pro/",
  },
  {
    id: "ristretto",
    label: "Ristretto",
    mode: "dark",
    dark: {
      bgPrimary: "#2c2525",
      bgSecondary: "#362d2d",
      bgHover: "#403535",
      textPrimary: "#f4f1ef",
      textSecondary: "#cbbdb8",
      borderColor: "#4a3c3c",
      accent: "#ff9f43",
      accentHover: "#f28a2e",
      danger: "#ff5f56",
      success: "#a9dc76",
    },
  },
  {
    id: "dracula",
    label: "Dracula",
    mode: "dark",
    dark: {
      bgPrimary: "#282a36",
      bgSecondary: "#303445",
      bgHover: "#3a3f52",
      textPrimary: "#f8f8f2",
      textSecondary: "#c5c8d6",
      borderColor: "#44475a",
      accent: "#bd93f9",
      accentHover: "#a87ded",
      danger: "#ff5555",
      success: "#50fa7b",
      syntax: {
        keyword: "#ff79c6",
        string: "#f1fa8c",
        number: "#bd93f9",
        type: "#8be9fd",
        definition: "#50fa7b",
        property: "#8be9fd",
        operator: "#ff79c6",
      },
    },
  },
  {
    id: "catppuccin",
    label: "Catppuccin Mocha",
    mode: "dark",
    dark: {
      bgPrimary: "#1e1e2e",
      bgSecondary: "#181825",
      bgHover: "#313244",
      textPrimary: "#cdd6f4",
      textSecondary: "#a6adc8",
      borderColor: "#585b70",
      accent: "#89b4fa",
      accentHover: "#89b4fa",
      danger: "#f38ba8",
      success: "#a6e3a1",
      warning: "#f9e2af",
      syntax: {
        keyword: "#cba6f7",
        string: "#a6e3a1",
        number: "#fab387",
      },
    },
    source: "https://catppuccin.com/palette/",
  },
  {
    id: "nord",
    label: "Nord",
    mode: "dark",
    dark: {
      bgPrimary: "#2e3440",
      bgSecondary: "#2e3440",
      bgHover: "#2e3440",
      textPrimary: "#d8dee9",
      textSecondary: "#c7cdd8",
      borderColor: "#3b4252",
      accent: "#88c0d0",
      accentHover: "#88c0d0",
      danger: "#bf616a",
      success: "#a3be8c",
      warning: "#ebcb8b",
      syntax: {
        keyword: "#81a1c1",
        string: "#a3be8c",
        number: "#b48ead",
        comment: "#616e88",
        type: "#88c0d0",
        definition: "#88c0d0",
        property: "#d8dee9",
      },
      terminal: {
        black: "#3b4252",
        "bright-black": "#4c566a",
        red: "#bf616a",
        "bright-red": "#bf616a",
        green: "#a3be8c",
        "bright-green": "#a3be8c",
        yellow: "#ebcb8b",
        "bright-yellow": "#ebcb8b",
        blue: "#81a1c1",
        "bright-blue": "#81a1c1",
        magenta: "#b48ead",
        "bright-magenta": "#b48ead",
        cyan: "#88c0d0",
        "bright-cyan": "#8fbcbb",
        white: "#e5e9f0",
        "bright-white": "#eceff4",
      },
    },
    source: "https://github.com/nordtheme/visual-studio-code",
  },
  {
    id: "gruvbox",
    label: "Gruvbox",
    mode: "dark",
    dark: {
      bgPrimary: "#282828",
      bgSecondary: "#32302f",
      bgHover: "#3c3836",
      textPrimary: "#ebdbb2",
      textSecondary: "#bdae93",
      borderColor: "#3c3836",
      accent: "#d79921",
      accentHover: "#c28515",
      danger: "#fb4934",
      success: "#b8bb26",
      syntax: {
        keyword: "#fb4934",
        string: "#b8bb26",
        number: "#d3869b",
        type: "#8ec07c",
        definition: "#fabd2f",
        property: "#83a598",
        operator: "#fb4934",
      },
    },
  },
  {
    id: "solarized",
    label: "Solarized",
    mode: "auto",
    light: {
      bgPrimary: "#fdf6e3",
      bgSecondary: "#f5efdc",
      bgHover: "#eee8d5",
      textPrimary: "#586e75",
      textSecondary: "#657b83",
      borderColor: "#e0d8c6",
      accent: "#268bd2",
      accentHover: "#1f78b3",
      danger: "#dc322f",
      success: "#859900",
    },
    dark: {
      bgPrimary: "#002b36",
      bgSecondary: "#073642",
      bgHover: "#0b3c4a",
      textPrimary: "#eee8d5",
      textSecondary: "#93a1a1",
      borderColor: "#18424a",
      accent: "#268bd2",
      accentHover: "#1f78b3",
      danger: "#dc322f",
      success: "#859900",
    },
  },
  {
    id: "tokyo",
    label: "Tokyo Night",
    mode: "dark",
    dark: {
      bgPrimary: "#1a1b26",
      bgSecondary: "#16161e",
      bgHover: "#16161e",
      textPrimary: "#a9b1d6",
      textSecondary: "#515670",
      borderColor: "#101014",
      accent: "#7aa2f7",
      accentHover: "#7aa2f7",
      danger: "#f7768e",
      success: "#73daca",
      warning: "#e0af68",
      syntax: {
        keyword: "#bb9af7",
        string: "#9ece6a",
        number: "#ff9e64",
        comment: "#a9b1d6",
        type: "#7aa2f7",
        definition: "#7aa2f7",
        property: "#7dcfff",
      },
      terminal: {
        black: "#363b54",
        "bright-black": "#363b54",
        red: "#f7768e",
        "bright-red": "#f7768e",
        green: "#73daca",
        "bright-green": "#73daca",
        yellow: "#e0af68",
        "bright-yellow": "#e0af68",
        blue: "#7aa2f7",
        "bright-blue": "#7aa2f7",
        magenta: "#bb9af7",
        "bright-magenta": "#bb9af7",
        cyan: "#7dcfff",
        "bright-cyan": "#7dcfff",
        white: "#787c99",
        "bright-white": "#acb0d0",
      },
    },
    source: "https://github.com/tokyo-night/tokyo-night-vscode-theme",
  },
  {
    id: "miasma",
    label: "Miasma",
    mode: "dark",
    dark: {
      bgPrimary: "#1f1f23",
      bgSecondary: "#29292f",
      bgHover: "#33333a",
      textPrimary: "#e5e5e5",
      textSecondary: "#b4b4b4",
      borderColor: "#3d3d45",
      accent: "#c9739c",
      accentHover: "#b8618c",
      danger: "#e06c75",
      success: "#98c379",
    },
  },
  {
    id: "github",
    label: "GitHub",
    mode: "auto",
    light: {
      bgPrimary: "#ffffff",
      bgSecondary: "#f6f8fa",
      bgHover: "#eaeef2",
      textPrimary: "#24292f",
      textSecondary: "#57606a",
      borderColor: "#d0d7de",
      accent: "#0969da",
      accentHover: "#0550ae",
      danger: "#cf222e",
      success: "#1a7f37",
    },
    dark: {
      bgPrimary: "#0d1117",
      bgSecondary: "#161b22",
      bgHover: "#21262d",
      textPrimary: "#c9d1d9",
      textSecondary: "#8b949e",
      borderColor: "#30363d",
      accent: "#2f81f7",
      accentHover: "#1f6feb",
      danger: "#f85149",
      success: "#3fb950",
    },
  },
  {
    id: "gotham",
    label: "Gotham",
    mode: "dark",
    dark: {
      bgPrimary: "#0b0f14",
      bgSecondary: "#111720",
      bgHover: "#18212b",
      textPrimary: "#cbd6e2",
      textSecondary: "#9bb0c3",
      borderColor: "#1f2a37",
      accent: "#5ccfe6",
      accentHover: "#48b8ce",
      danger: "#d26937",
      success: "#2aa889",
    },
  },
  {
    id: "one-dark-pro",
    label: "One Dark Pro",
    mode: "dark",
    dark: {
      bgPrimary: "#282c34",
      bgSecondary: "#21252b",
      bgHover: "#3e4451",
      textPrimary: "#abb2bf",
      textSecondary: "#5c6370",
      borderColor: "#3e4451",
      accent: "#61afef",
      accentHover: "#61afef",
      danger: "#e06c75",
      success: "#98c379",
      warning: "#e5c07b",
      syntax: {
        keyword: "#c678dd",
        string: "#98c379",
        number: "#d19a66",
        type: "#e5c07b",
        definition: "#61afef",
        property: "#e06c75",
        operator: "#56b6c2",
      },
    },
  },
  {
    id: "solarized-dark",
    label: "Solarized Dark",
    mode: "dark",
    dark: {
      bgPrimary: "#002b36",
      bgSecondary: "#002028",
      bgHover: "#073642",
      textPrimary: "#839496",
      textSecondary: "#586e75",
      borderColor: "#073642",
      accent: "#268bd2",
      accentHover: "#268bd2",
      danger: "#dc322f",
      success: "#859900",
      warning: "#b58900",
      syntax: {
        keyword: "#859900",
        string: "#2aa198",
        number: "#d33682",
        type: "#b58900",
        definition: "#268bd2",
        property: "#268bd2",
        operator: "#6c71c4",
      },
    },
  },
  {
    id: "solarized-light",
    label: "Solarized Light",
    mode: "light",
    light: {
      bgPrimary: "#fdf6e3",
      bgSecondary: "#eee8d5",
      bgHover: "#eee8d5",
      textPrimary: "#657b83",
      textSecondary: "#93a1a1",
      borderColor: "#d2cbb8",
      accent: "#268bd2",
      accentHover: "#268bd2",
      danger: "#dc322f",
      success: "#859900",
      warning: "#b58900",
      syntax: {
        keyword: "#859900",
        string: "#2aa198",
        number: "#d33682",
        type: "#b58900",
        definition: "#268bd2",
        property: "#268bd2",
        operator: "#6c71c4",
      },
    },
  },
  {
    id: "github-dark",
    label: "GitHub Dark",
    mode: "dark",
    dark: {
      bgPrimary: "#0d1117",
      bgSecondary: "#010409",
      bgHover: "#161b22",
      textPrimary: "#e6edf3",
      textSecondary: "#6e7681",
      borderColor: "#30363d",
      accent: "#58a6ff",
      accentHover: "#58a6ff",
      danger: "#f85149",
      success: "#3fb950",
      warning: "#d29922",
      syntax: {
        keyword: "#ff7b72",
        string: "#a5d6ff",
        number: "#79c0ff",
        type: "#ffa657",
        definition: "#d2a8ff",
        property: "#79c0ff",
        operator: "#ff7b72",
      },
    },
  },
  {
    id: "vscode-dark",
    label: "VS Code Dark Modern",
    mode: "dark",
    dark: {
      bgPrimary: "#1f1f1f",
      bgSecondary: "#181818",
      bgHover: "#2d2d2d",
      textPrimary: "#d4d4d4",
      textSecondary: "#858585",
      borderColor: "#3c3c3c",
      accent: "#0078d4",
      accentHover: "#0078d4",
      danger: "#f44747",
      success: "#4ec9b0",
      warning: "#ce9178",
      syntax: {
        keyword: "#569cd6",
        string: "#ce9178",
        number: "#b5cea8",
        type: "#4ec9b0",
        definition: "#dcdcaa",
        property: "#9cdcfe",
        operator: "#d4d4d4",
      },
    },
  },
  {
    id: "vscode-light",
    label: "VS Code Light Modern",
    mode: "light",
    light: {
      bgPrimary: "#ffffff",
      bgSecondary: "#f8f8f8",
      bgHover: "#f3f3f3",
      textPrimary: "#3b3b3b",
      textSecondary: "#767676",
      borderColor: "#e0e0e0",
      accent: "#005fb8",
      accentHover: "#005fb8",
      danger: "#e51400",
      success: "#008000",
      warning: "#bf8803",
      syntax: {
        keyword: "#0000ff",
        string: "#a31515",
        number: "#098658",
        type: "#267f99",
        definition: "#795e26",
        property: "#001080",
        operator: "#3b3b3b",
      },
    },
  },
  {
    id: "github-light",
    label: "GitHub Light",
    mode: "light",
    light: {
      bgPrimary: "#ffffff",
      bgSecondary: "#f6f8fa",
      bgHover: "#f6f8fa",
      textPrimary: "#24292f",
      textSecondary: "#6e7781",
      borderColor: "#d0d7de",
      accent: "#0969da",
      accentHover: "#0969da",
      danger: "#cf222e",
      success: "#1a7f37",
      warning: "#9a6700",
      syntax: {
        keyword: "#cf222e",
        string: "#0a3069",
        number: "#0550ae",
        type: "#e16209",
        definition: "#8250df",
        property: "#0550ae",
        operator: "#cf222e",
      },
    },
  },
  {
    id: "ayu-light",
    label: "Ayu Light",
    mode: "light",
    light: {
      bgPrimary: "#fafafa",
      bgSecondary: "#f3f4f5",
      bgHover: "#f3f4f5",
      textPrimary: "#575f66",
      textSecondary: "#abb0b6",
      borderColor: "#d9d8d7",
      accent: "#399ee6",
      accentHover: "#399ee6",
      danger: "#e65050",
      success: "#86b300",
      warning: "#f29718",
      syntax: {
        keyword: "#fa8d3e",
        string: "#86b300",
        number: "#a37acc",
        type: "#399ee6",
        definition: "#399ee6",
        property: "#4cbf99",
        operator: "#ed9366",
      },
    },
  },
  {
    id: "ayu-dark",
    label: "Ayu Dark",
    mode: "dark",
    dark: {
      bgPrimary: "#0d1017",
      bgSecondary: "#0b0e14",
      bgHover: "#131721",
      textPrimary: "#bfbdb6",
      textSecondary: "#3d424d",
      borderColor: "#1a2132",
      accent: "#39bae6",
      accentHover: "#39bae6",
      danger: "#f07178",
      success: "#aad94c",
      warning: "#ffb454",
      syntax: {
        keyword: "#ff8f40",
        string: "#aad94c",
        number: "#d2a6ff",
        type: "#39bae6",
        definition: "#39bae6",
        property: "#59c2ff",
        operator: "#f29668",
      },
    },
  },
  {
    id: "gruvbox-light",
    label: "Gruvbox Light",
    mode: "light",
    light: {
      bgPrimary: "#fbf1c7",
      bgSecondary: "#f2e5bc",
      bgHover: "#ebdbb2",
      textPrimary: "#3c3836",
      textSecondary: "#928374",
      borderColor: "#d5c4a1",
      accent: "#d79921",
      accentHover: "#d79921",
      danger: "#9d0006",
      success: "#79740e",
      warning: "#b57614",
      syntax: {
        keyword: "#9d0006",
        string: "#79740e",
        number: "#8f3f71",
        type: "#427b58",
        definition: "#b57614",
        property: "#076678",
        operator: "#9d0006",
      },
    },
  },
  {
    id: "rose-pine",
    label: "Rosé Pine",
    mode: "dark",
    dark: {
      bgPrimary: "#191724",
      bgSecondary: "#1f1d2e",
      bgHover: "#26233a",
      textPrimary: "#e0def4",
      textSecondary: "#8d89a4",
      borderColor: "#908caa",
      accent: "#c4a7e7",
      accentHover: "#c4a7e7",
      danger: "#eb6f92",
      success: "#9ccfd8",
      warning: "#f6c177",
      syntax: {
        keyword: "#31748f",
        string: "#9ccfd8",
        number: "#f6c177",
      },
    },
    source: "https://rosepinetheme.com/palette/",
  },
  {
    id: "catppuccin-latte",
    label: "Catppuccin Latte",
    mode: "light",
    light: {
      bgPrimary: "#eff1f5",
      bgSecondary: "#e6e9ef",
      bgHover: "#ccd0da",
      textPrimary: "#4c4f69",
      textSecondary: "#555871",
      borderColor: "#acb0be",
      accent: "#1e66f5",
      accentHover: "#1e66f5",
      danger: "#d20f39",
      success: "#40a02b",
      warning: "#df8e1d",
      syntax: {
        keyword: "#8839ef",
        string: "#40a02b",
        number: "#fe640b",
      },
    },
    source: "https://catppuccin.com/palette/",
  },
  {
    id: "everforest-dark",
    label: "Everforest Dark",
    mode: "dark",
    dark: {
      bgPrimary: "#2d353b",
      bgSecondary: "#343f44",
      bgHover: "#3d484d",
      textPrimary: "#d3c6aa",
      textSecondary: "#b3b5a4",
      borderColor: "#66766b",
      accent: "#a7c080",
      accentHover: "#a7c080",
      danger: "#e67e80",
      success: "#a7c080",
      warning: "#dbbc7f",
      syntax: {
        keyword: "#e69875",
        string: "#a7c080",
        number: "#d699b6",
      },
    },
    source: "https://github.com/sainnhe/everforest",
  },
  {
    id: "everforest-light",
    label: "Everforest Light",
    mode: "light",
    light: {
      bgPrimary: "#fdf6e3",
      bgSecondary: "#f4f0d9",
      bgHover: "#efebd4",
      textPrimary: "#5c6a72",
      textSecondary: "#5e6c73",
      borderColor: "#a6b0a0",
      accent: "#8da101",
      accentHover: "#8da101",
      danger: "#f85552",
      success: "#8da101",
      warning: "#dfa000",
      syntax: {
        keyword: "#f57d26",
        string: "#8da101",
        number: "#df69ba",
      },
    },
    source: "https://github.com/sainnhe/everforest",
  },
  {
    id: "rose-pine-dawn",
    label: "Rosé Pine Dawn",
    mode: "light",
    light: {
      bgPrimary: "#faf4ed",
      bgSecondary: "#fffaf3",
      bgHover: "#f2e9e1",
      textPrimary: "#464261",
      textSecondary: "#6c6780",
      borderColor: "#797593",
      accent: "#d7827e",
      accentHover: "#d7827e",
      danger: "#b4637a",
      success: "#56949f",
      warning: "#ea9d34",
      syntax: {
        keyword: "#286983",
        string: "#56949f",
        number: "#ea9d34",
      },
    },
    source: "https://rosepinetheme.com/palette/",
  },
  {
    id: "graphite",
    label: "Graphite",
    mode: "dark",
    dark: {
      bgPrimary: "#202326",
      bgSecondary: "#292d31",
      bgHover: "#32383d",
      textPrimary: "#e6e8ea",
      textSecondary: "#a6adb4",
      borderColor: "#66717b",
      accent: "#93b9cc",
      accentHover: "#93b9cc",
      danger: "#e3a49e",
      success: "#a7c6b0",
      warning: "#ddca92",
      syntax: {
        keyword: "#93b9cc",
        string: "#a7c6b0",
        number: "#ddca92",
      },
    },
  },
  {
    id: "paper",
    label: "Paper",
    mode: "light",
    light: {
      bgPrimary: "#f8f7f3",
      bgSecondary: "#efeee8",
      bgHover: "#e6e4dc",
      textPrimary: "#292e31",
      textSecondary: "#5f676c",
      borderColor: "#a9afb0",
      accent: "#376a7d",
      accentHover: "#376a7d",
      danger: "#a63c39",
      success: "#326947",
      warning: "#896016",
      syntax: {
        keyword: "#376a7d",
        string: "#326947",
        number: "#896016",
      },
    },
  },
  {
    id: "accessible-dark",
    label: "Accessible Dark",
    mode: "dark",
    dark: {
      bgPrimary: "#080b0d",
      bgSecondary: "#11171b",
      bgHover: "#1c2429",
      textPrimary: "#ffffff",
      textSecondary: "#dce4e9",
      borderColor: "#adbfc9",
      accent: "#8addff",
      accentHover: "#8addff",
      danger: "#ffb2b2",
      success: "#97e6ac",
      warning: "#ffe48a",
      syntax: {
        keyword: "#8addff",
        string: "#97e6ac",
        number: "#ffe48a",
      },
    },
  },
  {
    id: "accessible-light",
    label: "Accessible Light",
    mode: "light",
    light: {
      bgPrimary: "#ffffff",
      bgSecondary: "#f3f5f6",
      bgHover: "#e7ecef",
      textPrimary: "#11191f",
      textSecondary: "#35434c",
      borderColor: "#526571",
      accent: "#004b76",
      accentHover: "#004b76",
      danger: "#8c1725",
      success: "#155b2e",
      warning: "#735100",
      syntax: {
        keyword: "#004b76",
        string: "#155b2e",
        number: "#735100",
      },
    },
  },
  {
    id: "oled",
    label: "OLED Night",
    mode: "dark",
    dark: {
      bgPrimary: "#000000",
      bgSecondary: "#090c0f",
      bgHover: "#14191d",
      textPrimary: "#f1f5f7",
      textSecondary: "#a8b6be",
      borderColor: "#526773",
      accent: "#6bd8df",
      accentHover: "#6bd8df",
      danger: "#f6a4a6",
      success: "#8bd7a3",
      warning: "#e8cf88",
      syntax: {
        keyword: "#6bd8df",
        string: "#8bd7a3",
        number: "#e8cf88",
      },
    },
  },
  {
    id: "petrol",
    label: "Petrol & Copper",
    mode: "dark",
    dark: {
      bgPrimary: "#102b30",
      bgSecondary: "#18373c",
      bgHover: "#24474b",
      textPrimary: "#f0e8da",
      textSecondary: "#b7c3bb",
      borderColor: "#577b7d",
      accent: "#d99a6c",
      accentHover: "#d99a6c",
      danger: "#f5a7a2",
      success: "#a8c89a",
      warning: "#e7ca87",
      syntax: {
        keyword: "#d99a6c",
        string: "#a8c89a",
        number: "#e7ca87",
      },
    },
  },
  {
    id: "petrol-light",
    label: "Ivory & Petrol",
    mode: "light",
    light: {
      bgPrimary: "#f0e8da",
      bgSecondary: "#e5ddcd",
      bgHover: "#dad3c3",
      textPrimary: "#18363b",
      textSecondary: "#4a605b",
      borderColor: "#9baca1",
      accent: "#89532f",
      accentHover: "#89532f",
      danger: "#a0403e",
      success: "#396c4a",
      warning: "#805e21",
      syntax: {
        keyword: "#246372",
        string: "#3b6c4b",
        number: "#89532f",
      },
    },
  },
  {
    id: "aubergine",
    label: "Aubergine & Gold",
    mode: "dark",
    dark: {
      bgPrimary: "#291f30",
      bgSecondary: "#352b3d",
      bgHover: "#42364b",
      textPrimary: "#f4ebdd",
      textSecondary: "#c1b2c0",
      borderColor: "#7e647e",
      accent: "#e2bc68",
      accentHover: "#e2bc68",
      danger: "#f0a3a6",
      success: "#aeca9a",
      warning: "#e2bc68",
      syntax: {
        keyword: "#cfafd9",
        string: "#e2bc68",
        number: "#99cbd2",
      },
    },
  },
  {
    id: "cobalt2",
    label: "Cobalt2",
    mode: "dark",
    dark: {
      bgPrimary: "#193549",
      bgSecondary: "#15232d",
      bgHover: "#234e68",
      textPrimary: "#ffffff",
      textSecondary: "#a6c7dc",
      borderColor: "#547d99",
      accent: "#ffc600",
      accentHover: "#ffc600",
      danger: "#ff8c8c",
      success: "#a5ff90",
      warning: "#ffc600",
      syntax: {
        keyword: "#ff9d00",
        string: "#a5ff90",
        number: "#ff628c",
      },
    },
    source: "https://github.com/wesbos/cobalt2-vscode",
  },
  {
    id: "burgundy",
    label: "Burgundy & Rose",
    mode: "dark",
    dark: {
      bgPrimary: "#321f29",
      bgSecondary: "#402b34",
      bgHover: "#503743",
      textPrimary: "#f4e7dc",
      textSecondary: "#cdb2bc",
      borderColor: "#8d6c79",
      accent: "#e3a6b1",
      accentHover: "#e3a6b1",
      danger: "#ffbd78",
      success: "#a5ccb1",
      warning: "#ecd68c",
      syntax: {
        keyword: "#e3a6b1",
        string: "#a5ccb1",
        number: "#ecd68c",
      },
    },
  },
  {
    id: "porcelain",
    label: "Porcelain, Indigo & Persimmon",
    mode: "light",
    light: {
      bgPrimary: "#f6f1e7",
      bgSecondary: "#e9e4d8",
      bgHover: "#ded9cc",
      textPrimary: "#304567",
      textSecondary: "#546071",
      borderColor: "#969cac",
      accent: "#b94e28",
      accentHover: "#b94e28",
      danger: "#913449",
      success: "#456c42",
      warning: "#7f6118",
      syntax: {
        keyword: "#304567",
        string: "#476e5f",
        number: "#b94e28",
      },
    },
  },
  {
    id: "synthwave-84",
    label: "SynthWave ’84",
    mode: "dark",
    dark: {
      bgPrimary: "#262335",
      bgSecondary: "#241b2f",
      bgHover: "#342b48",
      textPrimary: "#f4f0ff",
      textSecondary: "#b7b0d0",
      borderColor: "#736282",
      accent: "#ff7edb",
      accentHover: "#ff7edb",
      danger: "#ff9c93",
      success: "#72f1b8",
      warning: "#fede5d",
      syntax: {
        keyword: "#fede5d",
        string: "#ff8b39",
        number: "#36f9f6",
      },
    },
    glow: true,
    source: "https://github.com/robb0wen/synthwave-vscode",
  },
  {
    id: "colour-friendly-dark",
    label: "Colour-friendly Dark",
    mode: "dark",
    dark: {
      bgPrimary: "#202326",
      bgSecondary: "#292d31",
      bgHover: "#32383d",
      textPrimary: "#e6e8ea",
      textSecondary: "#a6adb4",
      borderColor: "#66717b",
      accent: "#93b9cc",
      accentHover: "#93b9cc",
      danger: "#f09769",
      success: "#56b4e9",
      warning: "#e6b65a",
      syntax: {
        keyword: "#93b9cc",
        string: "#a7c6b0",
        number: "#ddca92",
      },
    },
  },
  {
    id: "colour-friendly-light",
    label: "Colour-friendly Light",
    mode: "light",
    light: {
      bgPrimary: "#f8f7f3",
      bgSecondary: "#efeee8",
      bgHover: "#e6e4dc",
      textPrimary: "#292e31",
      textSecondary: "#5f676c",
      borderColor: "#a9afb0",
      accent: "#376a7d",
      accentHover: "#376a7d",
      danger: "#b44500",
      success: "#0072b2",
      warning: "#8c5a00",
      syntax: {
        keyword: "#376a7d",
        string: "#326947",
        number: "#896016",
      },
    },
  },
  {
    id: "turbo-pascal",
    label: "Turbo Pascal (Original)",
    mode: "dark",
    dark: {
      bgPrimary: "#000088",
      bgSecondary: "#5c5c5c",
      bgHover: "#000066",
      textPrimary: "#aaaaaa",
      textSecondary: "#c0c0c0",
      borderColor: "#606060",
      accent: "#ffff00",
      accentHover: "#ffff00",
      danger: "#aa0000",
      success: "#00aa00",
      warning: "#aaaa00",
      syntax: {
        keyword: "#ffffff",
        string: "#00ffff",
        number: "#aaaa00",
        comment: "#00ff00",
        type: "#ffff00",
        definition: "#ffff00",
        property: "#aaaaaa",
      },
      terminal: {
        black: "#000000",
        "bright-black": "#555555",
        red: "#aa0000",
        "bright-red": "#ff5555",
        green: "#00aa00",
        "bright-green": "#55ff55",
        yellow: "#aaaa00",
        "bright-yellow": "#ffff55",
        blue: "#000088",
        "bright-blue": "#4848dd",
        magenta: "#aa00aa",
        "bright-magenta": "#ff55ff",
        cyan: "#00aaaa",
        "bright-cyan": "#55ffff",
        white: "#aaaaaa",
        "bright-white": "#ffffff",
      },
    },
    source: "https://github.com/jsolarz/Modern-Turbo-UI-Color-Scheme",
  },
  {
    id: "as400",
    label: "AS/400 Green Screen (5250)",
    mode: "dark",
    dark: {
      bgPrimary: "#000000",
      bgSecondary: "#000000",
      bgHover: "#001a00",
      textPrimary: "#00ff00",
      textSecondary: "#009900",
      borderColor: "#003300",
      accent: "#00ff00",
      accentHover: "#00ff00",
      danger: "#00ff00",
      success: "#00cc00",
      warning: "#00dd00",
      monochrome: true,
      syntax: {
        keyword: "#00ff00",
        string: "#00dd00",
        number: "#00ee00",
        comment: "#007700",
        type: "#00ff00",
        definition: "#00cc00",
        property: "#00cc00",
      },
      terminal: {
        black: "#000000",
        red: "#00ff00",
        green: "#00cc00",
        yellow: "#00dd00",
        blue: "#00bb00",
        magenta: "#00ee00",
        cyan: "#00cc00",
        white: "#00dd00",
        "bright-black": "#009900",
        "bright-red": "#00ff00",
        "bright-green": "#00ff00",
        "bright-yellow": "#00ff00",
        "bright-blue": "#00ee00",
        "bright-magenta": "#00ff00",
        "bright-cyan": "#00ee00",
        "bright-white": "#00ff00",
      },
    },
    source: "https://github.com/jordandiazdiaz/as400-cursor",
  },
  {
    id: "lumon",
    label: "Lumon",
    mode: "dark",
    dark: {
      bgPrimary: "#1b2d40",
      bgSecondary: "#1b2d40",
      bgHover: "#1b2d40",
      textPrimary: "#d6e2ee",
      textSecondary: "#4a6b80",
      borderColor: "#4a6b80",
      accent: "#4d9ed3",
      accentHover: "#4d9ed3",
      danger: "#4d86b0",
      success: "#5e95bc",
      warning: "#6fa4c9",
      syntax: {
        keyword: "#6fb8e3",
        string: "#6fb8e3",
        number: "#f2fcff",
        comment: "#4a6b80",
        type: "#b4e4f6",
        definition: "#4d9ed3",
        property: "#4d9ed3",
      },
      terminal: {
        black: "#1b2d40",
        "bright-black": "#4a6b80",
        red: "#4d86b0",
        "bright-red": "#73a6cb",
        green: "#5e95bc",
        "bright-green": "#86b7d8",
        yellow: "#6fa4c9",
        "bright-yellow": "#9dcae5",
        blue: "#6fb8e3",
        "bright-blue": "#f2fcff",
        magenta: "#8bc9eb",
        "bright-magenta": "#b1d8ee",
        cyan: "#b4e4f6",
        "bright-cyan": "#d1eef8",
        white: "#d6e2ee",
        "bright-white": "#ffffff",
      },
    },
    source: "https://github.com/OldJobobo/lumon-theme.vscode",
  },
  {
    id: "noctis",
    label: "Noctis",
    mode: "dark",
    dark: {
      bgPrimary: "#052529",
      bgSecondary: "#041d20",
      bgHover: "#073940",
      textPrimary: "#b2cacd",
      textSecondary: "#929ea0",
      borderColor: "#0e6671",
      accent: "#16b0ab",
      accentHover: "#16b0ab",
      danger: "#e66533",
      success: "#49e9a6",
      warning: "#e4b781",
      syntax: {
        keyword: "#df769b",
        string: "#49e9a6",
        number: "#7060eb",
        comment: "#5b858b",
        type: "#d67e5c",
        definition: "#16a3b6",
        property: "#b2cacd",
      },
      terminal: {
        black: "#324a4d",
        "bright-black": "#47686c",
        red: "#e66533",
        "bright-red": "#e97749",
        green: "#49e9a6",
        "bright-green": "#60ebb1",
        yellow: "#e4b781",
        "bright-yellow": "#e69533",
        blue: "#49ace9",
        "bright-blue": "#60b6eb",
        magenta: "#df769b",
        "bright-magenta": "#e798b3",
        cyan: "#49d6e9",
        "bright-cyan": "#60dbeb",
        white: "#b2cacd",
        "bright-white": "#c1d4d7",
      },
    },
    source: "https://github.com/liviuschera/noctis",
  },
  {
    id: "noctis-lux",
    label: "Noctis Lux",
    mode: "light",
    light: {
      bgPrimary: "#fef8ec",
      bgSecondary: "#f9f1e1",
      bgHover: "#f2edde",
      textPrimary: "#005661",
      textSecondary: "#929ea0",
      borderColor: "#00c6e0",
      accent: "#008080",
      accentHover: "#008080",
      danger: "#e34e1c",
      success: "#00b368",
      warning: "#f49725",
      syntax: {
        keyword: "#ff5792",
        string: "#00b368",
        number: "#5842ff",
        comment: "#8ca6a6",
        type: "#b3694d",
        definition: "#0095a8",
        property: "#005661",
      },
      terminal: {
        black: "#003b42",
        "bright-black": "#004d57",
        red: "#e34e1c",
        "bright-red": "#ff4000",
        green: "#00b368",
        "bright-green": "#00d17a",
        yellow: "#f49725",
        "bright-yellow": "#ff8c00",
        blue: "#0094f0",
        "bright-blue": "#0fa3ff",
        magenta: "#ff5792",
        "bright-magenta": "#ff6b9f",
        cyan: "#00bdd6",
        "bright-cyan": "#00cbe6",
        white: "#8ca6a6",
        "bright-white": "#bbc3c4",
      },
    },
    source: "https://github.com/liviuschera/noctis",
  },
  {
    id: "bearded-arc",
    label: "Bearded Arc",
    mode: "dark",
    dark: {
      bgPrimary: "#1c2433",
      bgSecondary: "#181f2c",
      bgHover: "#253043",
      textPrimary: "#d3d8e1",
      textSecondary: "#d3d8e1",
      borderColor: "#11161f",
      accent: "#8196b5",
      accentHover: "#8196b5",
      danger: "#e35535",
      success: "#3cec85",
      warning: "#eacd61",
      syntax: {
        keyword: "#8196b5",
        string: "#3cec85",
        number: "#ff955c",
        comment: "#54617b",
        type: "#a4ef58",
        definition: "#69c3ff",
        property: "#d3d8e1",
      },
      terminal: {
        black: "#1c2433",
        "bright-black": "#69c3ff",
        red: "#e35535",
        "bright-red": "#e35535",
        green: "#3cec85",
        "bright-green": "#3cec85",
        yellow: "#eacd61",
        "bright-yellow": "#eacd61",
        blue: "#69c3ff",
        "bright-blue": "#69c3ff",
        magenta: "#f38cec",
        "bright-magenta": "#f38cec",
        cyan: "#22ecdb",
        "bright-cyan": "#22ecdb",
        white: "#d3d8e1",
        "bright-white": "#d3d8e1",
      },
    },
    source: "https://github.com/BeardedBear/bearded-theme",
  },
  {
    id: "tokyo-night-storm",
    label: "Tokyo Night Storm",
    mode: "dark",
    dark: {
      bgPrimary: "#24283b",
      bgSecondary: "#1f2335",
      bgHover: "#1f2335",
      textPrimary: "#a9b1d6",
      textSecondary: "#545c7e",
      borderColor: "#1b1e2e",
      accent: "#7aa2f7",
      accentHover: "#7aa2f7",
      danger: "#f7768e",
      success: "#73daca",
      warning: "#e0af68",
      syntax: {
        keyword: "#bb9af7",
        string: "#9ece6a",
        number: "#ff9e64",
        comment: "#a9b1d6",
        type: "#7aa2f7",
        definition: "#7aa2f7",
        property: "#7dcfff",
      },
      terminal: {
        black: "#414868",
        "bright-black": "#414868",
        red: "#f7768e",
        "bright-red": "#f7768e",
        green: "#73daca",
        "bright-green": "#73daca",
        yellow: "#e0af68",
        "bright-yellow": "#e0af68",
        blue: "#7aa2f7",
        "bright-blue": "#7aa2f7",
        magenta: "#bb9af7",
        "bright-magenta": "#bb9af7",
        cyan: "#7dcfff",
        "bright-cyan": "#7dcfff",
        white: "#8089b3",
        "bright-white": "#a9b1d6",
      },
    },
    source: "https://github.com/tokyo-night/tokyo-night-vscode-theme",
  },
  {
    id: "tokyo-night-light",
    label: "Tokyo Night Light",
    mode: "light",
    light: {
      bgPrimary: "#e6e7ed",
      bgSecondary: "#d6d8df",
      bgHover: "#d6d8df",
      textPrimary: "#343b59",
      textSecondary: "#707280",
      borderColor: "#c1c2c7",
      accent: "#2959aa",
      accentHover: "#2959aa",
      danger: "#8c4351",
      success: "#33635c",
      warning: "#8f5e15",
      syntax: {
        keyword: "#65359d",
        string: "#385f0d",
        number: "#965027",
        comment: "#343b59",
        type: "#2959aa",
        definition: "#2959aa",
        property: "#0f4b6e",
      },
      terminal: {
        black: "#343b58",
        "bright-black": "#343b58",
        red: "#8c4351",
        "bright-red": "#8c4351",
        green: "#33635c",
        "bright-green": "#33635c",
        yellow: "#8f5e15",
        "bright-yellow": "#8f5e15",
        blue: "#2959aa",
        "bright-blue": "#2959aa",
        magenta: "#7b43ba",
        "bright-magenta": "#7b43ba",
        cyan: "#006c86",
        "bright-cyan": "#006c86",
        white: "#707280",
        "bright-white": "#707280",
      },
    },
    source: "https://github.com/tokyo-night/tokyo-night-vscode-theme",
  },
  {
    id: "catppuccin-frappe",
    label: "Catppuccin Frappé",
    mode: "dark",
    dark: {
      bgPrimary: "#303446",
      bgSecondary: "#292c3c",
      bgHover: "#414559",
      textPrimary: "#c6d0f5",
      textSecondary: "#a5adce",
      borderColor: "#626880",
      accent: "#8caaee",
      accentHover: "#babbf1",
      danger: "#e78284",
      success: "#a6d189",
      warning: "#e5c890",
      syntax: {
        keyword: "#ca9ee6",
        string: "#a6d189",
        number: "#ef9f76",
        type: "#e5c890",
        definition: "#8caaee",
        property: "#81c8be",
      },
    },
    source: "https://github.com/catppuccin/palette",
  },
  {
    id: "catppuccin-macchiato",
    label: "Catppuccin Macchiato",
    mode: "dark",
    dark: {
      bgPrimary: "#24273a",
      bgSecondary: "#1e2030",
      bgHover: "#363a4f",
      textPrimary: "#cad3f5",
      textSecondary: "#a5adcb",
      borderColor: "#5b6078",
      accent: "#8aadf4",
      accentHover: "#b7bdf8",
      danger: "#ed8796",
      success: "#a6da95",
      warning: "#eed49f",
      syntax: {
        keyword: "#c6a0f6",
        string: "#a6da95",
        number: "#f5a97f",
        type: "#eed49f",
        definition: "#8aadf4",
        property: "#8bd5ca",
      },
    },
    source: "https://github.com/catppuccin/palette",
  },
];
// Full keeps the familiar palette, with a separately selectable neon treatment.
const synthwave = WEB_THEME_PRESETS.find(
  (theme) => theme.id === "synthwave-84",
)!;
WEB_THEME_PRESETS.splice(WEB_THEME_PRESETS.indexOf(synthwave) + 1, 0, {
  ...synthwave,
  id: "synthwave-84-full",
  label: "SynthWave ’84 Full",
});

// Explicit variants and automatic pairs use the same palette data.
for (const family of ["solarized", "github"]) {
  const automatic = WEB_THEME_PRESETS.find((t) => t.id === family)!;
  for (const mode of ["light", "dark"] as const) {
    const variant = WEB_THEME_PRESETS.find((t) => t.id === family + "-" + mode);
    if (variant) variant[mode] = automatic[mode];
  }
}
// Preserve Visual's explicit black Classic bundle, distinct from each skin's adaptive Default.
WEB_THEME_PRESETS.push({
  id: "piclaw-classic",
  label: "PiClaw Classic",
  mode: "dark",
  dark: { ...WEB_THEME_PRESETS[0].dark! },
});
export const WEB_THEME_ALIASES: Record<string, string> = {
  auto: "default",
  drac: "dracula",
  catpp: "catppuccin",
  "catppuccin-mocha": "catppuccin",
  gruv: "gruvbox",
  "gruvbox-dark": "gruvbox",
  "tokyo-night": "tokyo",
  catpuccin: "catppuccin",
  "catpuccin-latte": "catppuccin-latte",
  "as400-green-screen": "as400",
  "as-400": "as400",
  bearded: "bearded-arc",
  turbo: "turbo-pascal",
  "monokai-original": "monokai",
  synthwave: "synthwave-84",
  "synthwave-full": "synthwave-84-full",
  "petrol-copper": "petrol",
  "aubergine-gold": "aubergine",
  "burgundy-rose": "burgundy",
  "ivory-petrol": "petrol-light",
};
export function normaliseWebThemeId(value: unknown): string | null {
  const id = String(value ?? "")
    .trim()
    .toLowerCase();
  const key = WEB_THEME_ALIASES[id] || id;
  return WEB_THEME_PRESETS.some((t) => t.id === key) ? key : null;
}
